namespace BraspagApiDotNetSdk.Contracts.Enum
{
	public enum ProviderEnum
	{	   
        Cielo,
        Redecard,
        Simulado,
        Bradesco,
        Itau,
        Brb,
        Caixa,
        BancoDoBrasil,
        Citibank,
        Santander,
        Hsbc,
        SafetyPay,
        RedeSiTef,
        CieloSiTef,
        SantanderSiTef,
        Rede,
        Policard,
        Banorte,
        Sub1,
        BancoDoBrasil2,
        Cielo30,
        Bradesco2,
        Transbank,
        RiachueloSiTef
	}
}
