namespace BraspagApiDotNetSdk.Contracts.Enum
{
	public enum ProviderEnum
	{
        Cielo,
        Redecard,
        Simulado,
        Bradesco,
        Itau,
        Brb,
        Caixa,
        BancoDoBrasil,
        Citibank,
        Santander,
        Hsbc,
        SafetyPay,
        CieloSiTef,
        RedeSiTef,
        SantanderSiTef,
        Rede,
        Banorte,
        Sub1,
        BancoDoBrasil2,
        Cielo30,
        Bradesco2,
        Transbank,
        RiachueloSiTef,
        DmCard,
        Citibank2,
        ItauShopline,
        Banese,
        GlobalPayments,
        FirstData,
        Getnet
    }
}
